# test push

on: workflow_call

jobs:
  pr-validation:
    if: ${{ !contains(github.event.pull_request.body, '[skip-validate-pr]') && !contains(github.event.pull_request.title, '[skip-validate-pr]') }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions-ecosystem/action-regex-match@d50fd2e7a37d0e617aea3d7ada663bd56862b9cc
        id: regex-match-gus-wi
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '@W-\d{7,8}@'
          flags: gm
      - uses: actions-ecosystem/action-regex-match@d50fd2e7a37d0e617aea3d7ada663bd56862b9cc
        id: regex-match-gh-issue
        with:
          text: ${{ github.event.pull_request.body }}
          regex: "#[0-9]+"
          flags: gm
      - name: fail
        if: |
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          github.event.pull_request.user.login != 'svc-cli-bot' &&
          steps.regex-match-gus-wi.outputs.match == '' &&
          steps.regex-match-gh-issue.outputs.match == ''
        run: |
          echo "PR does not reference work item or github issue."
          echo "GUS WIs should be wrapped in @s, ex: @W-12345678@ or [@W-12345678@](https://some-url)"
          exit 1
      - name: output success
        if: |
          steps.regex-match-gus-wi.outputs.match != '' ||
          steps.regex-match-gh-issue.outputs.match != ''
        run: |
          echo "PR references ${{ steps.regex-match-gus-wi.outputs.match }} ${{ steps.regex-match-gh-issue.outputs.match }}"
